### ISSUE TITLE
Upload

### ISSUE THREAD

**Issue by FangYuan717** [michaelwitting/RepoRT#149]
Hi, I'm trying to upload the 48 datasets I collected earlier, but using the new web app always gets stuck on review retention times. It occurs as in the two images below, the top one uses the example 0259_rtdata.tsv and the progress is always at 0, and the bottom one uses the uploaded data and the yellow button doesn't respond when tapped.
![240913](https://github.com/user-attachments/assets/71eb1cef-3db7-47d6-aa80-9c7c6bbb6798)
![240913-2](https://github.com/user-attachments/assets/98126f35-3374-44d6-8ddf-5d065cbe5c0a)

Also, it seems that new additives are not supported in the current ‘eluent’, for example, one of my datasets uses heptafluorobutyric acid  as additive, but it seems that I can only choose the existing additive options.

Looking forward to the answer~

**Comment by f-kretschmer** [comment]
First, thanks for uploading your data! I am out of the office right now (for two weeks), I will get back to you as soon as possible.

**Comment by FangYuan717** [comment]
Hope you have a great time away, and I'll look forward to hearing back from you when you're back in the office.

**Comment by BrinkiBlink** [comment]
Hey i just wanted to update you on this issue. We are currently working for a fix and hope to provide a solution soon.

**Comment by FangYuan717** [comment]
Hi, thank you for the update. I appreciate your efforts and look forward to the solution.

**Comment by BrinkiBlink** [comment]
Hey, we found a bug that might be the reason for your error. You can try again and let us know if you still encounter any issues. If that's the case, please use the newly added "download current progress" button (accessible via the gear wheel) and provide your dataset either directly here or via report@uni-jena.de.

**Comment by FangYuan717** [comment]
Hi, thank you for your update. After the recent changes, I can now use the blue button to perform a quick check during the RETENTION TIMES phase, which is an improvement compared to my previous experience. However, after the blue button check is done, the data still cannot be submitted (please see the attached screenshot). And clicking the "check" button does not yield any response.

[cid:b806cded-0a3a-4c1a-bbcf-554faee08819]
As per your suggestion, I have sent the pending upload data to ***@***.******@***.***>.

________________________________
发件人: Leopold Brinkmann ***@***.***>
发送时间: 2024年10月8日 19:40
收件人: michaelwitting/RepoRT ***@***.***>
抄送: FangYuan717 ***@***.***>; Author ***@***.***>
主题: Re: [michaelwitting/RepoRT] Upload (Issue #149)


Hey, we found a bug that might be the reason for your error. You can try again and let us know if you still encounter any issues. If that's the case, please use the newly added "download current progress" button (accessible via the gear wheel) and provide your dataset either directly here or via ***@***.******@***.***>.

―

**Comment by f-kretschmer** [comment]
Just to let you know, "heptafluorobutyric acid" has now been added as additive. I will keep this issue open until the new datasets are integrated into RepoRT.

**Comment by f-kretschmer** [comment]
Now all datasets are merged, but there are some remaining questions:

1. dataset ROASMI_43 (0408) has the same publication source and (almost) equal retention time data as our dataset IPB_Halle (0003), is this a duplicate? If so, the metadata is different.
2. Is there a publication source for dataset ST001610 (0395)?

**Comment by FangYuan717** [comment]
Thanks for your feedbacks.
1.  I checked the original literature and there are two LC-MS systems used in the article (please see the attached figure). The metadata of ROASMI_43 (0408) is the information for system B.
![图片](https://github.com/user-attachments/assets/ae93fce4-58ce-4654-b78a-df821753a63d)
2. ST001610(0395) is sourced from the Metabolomics Workbench, but I did'nt find its publication.

**Comment by FangYuan717** [comment]
> Just to let you know, "heptafluorobutyric acid" has now been added as additive. I will keep this issue open until the new datasets are integrated into RepoRT.

Hi, I tried three times and was unable to upload the last dataset (it is the dataset which used "heptafluorobutyric acid"). Each time I uploaded I got stuck at the bottom image, maybe because of the large dataset (1953 records in total)?
![图片](https://github.com/user-attachments/assets/4ef12438-0c2c-4855-ad94-2d2f69073d70)

**Comment by BrinkiBlink** [comment]
i suggest to use the "download data" button and add the large dataset manually. To understand what went wrong here it would be great if you could provide us with the network/console tab of your brwoser (f12 should open menu where you can browse network and console)

**Comment by BrinkiBlink** [comment]
Thank you for the screenshot. We will look further into it and check if we can set a new threshold for larger datasets. Have you downloaded your set and can you provide it via email?

**Comment by f-kretschmer** [comment]
Hi Fangyuan Sun,

Sorry for the delay but everything should now be fixed. There was a limit on dataset size preventing the submission, which has now been adapted. Could you try again one last time with the ROASMI_86 dataset?

**Comment by FangYuan717** [comment]
Thank you for addressing the dataset size limit issue. I have successfully uploaded the ROASMI_86 dataset.
