### ISSUE TITLE
wrong particle size == 100

### ISSUE THREAD

**Issue by cloudcell** [michaelwitting/RepoRT#198]
https://github.com/michaelwitting/RepoRT/blob/713272555428663cf8de4a2e93b0accb0f3c55f1/raw_data/0260/0260_metadata.yaml#L7

The associated tsv file has to be corrected as well.

**Comment by cloudcell** [comment]
Based on this: [https://www.chromforum.org/viewtopic.php?t=6914](url) I think this is a pore size rather than a particle size.

**Comment by cloudcell** [comment]
Also, I think this
https://github.com/michaelwitting/RepoRT/blob/713272555428663cf8de4a2e93b0accb0f3c55f1/raw_data/0260/0260_metadata.yaml#L6
Should be 3 mm instead of 1 mm, do you agree?

**Comment by f-kretschmer** [comment]
Thank you very much, the correct values are now used everywhere.
